- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get installed version
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          export PATH=/usr/local/bin:$PATH
          if command -v session-manager-plugin &> /dev/null; then
            session-manager-plugin --version
          fi
        executable: /bin/bash
      register: get_installed_version
      changed_when: false

    - name: Set installed version
      ansible.builtin.set_fact:
        installed_version: >-
          {{ get_installed_version.stdout | regex_search(".+\..+\..+") }}

    - name: Get latest version
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          curl --silent --fail-with-body {{ github }} \
            | sed -n -E 's/.*"tag_name": "(.+)",.*/\1/p'
        executable: /bin/bash
      vars:
        github: https://api.github.com/repos/aws/session-manager-plugin/releases/latest
      register: get_latest_version
      changed_when: false

    - name: Set latest version
      ansible.builtin.set_fact:
        latest_version: >-
          {{ get_latest_version.stdout | regex_search(".+\..+\..+") }}

    - name: Verify installed version correct
      ansible.builtin.assert:
        that:
          - installed_version == latest_version
        fail_msg: >-
          `installed_version` is "{{ installed_version }}", but must be "{{ latest_version }}".
